version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 10 23 * *"
      timezone: "America/Mexico_City"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(deps)"
    groups:
      safe-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "major"
      safe-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 10 23 * *"
      timezone: "America/Mexico_City"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(actions)"
    groups:
      safe-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "major"
      safe-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "major"
